# Initial delay in seconds before checking if there are
# players online (to give players time to join the server)
initial_delay_seconds: 60

# The amount of seconds to wait, after the last player left the
# server, before shutting down the server.
# If any players join's the server again within this time, the
# server won't be shut down.
shutdown_delay_seconds: 300

# Does what it says
enable_logging: true